# Generated by Django 5.2.1 on 2025-06-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfig',
            name='claude_response',
            field=models.TextField(blank=True, help_text="Claude's reasoning for the schedule", null=True),
        ),
    ]
