# Generated by Django 5.2.1 on 2025-10-13 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_scheduleconfig_claude_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Summer Schedule', 'Holiday Coverage')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of this template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive templates are hidden from selection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday, 6=Sunday)')),
                ('total_required_staff', models.IntegerField(default=1)),
                ('required_rank_1', models.IntegerField(default=0)),
                ('required_rank_2', models.IntegerField(default=0)),
                ('required_rank_3', models.IntegerField(default=0)),
                ('required_rank_4', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shifttype')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.shifttemplate')),
            ],
            options={
                'ordering': ['weekday', 'shift_type__start_time'],
                'unique_together': {('template', 'weekday', 'shift_type')},
            },
        ),
    ]
